### PR TITLE
added new model in order to provide urgent messages/announcements to …

### PR DESCRIPTION
**Pull request by Karinon**
…the web interface.

Still needs to be added to the create tables-thingie

### CODE REVIEW

**Comment by antarcticrainforest** [comment]
Would you mind creating a screenshot and attaching it here? Also, how does this work in practice?

**Comment by Karinon** [comment]
Screenshot from 2022-11-07 09-54-52
Screenshot from 2022-11-07 09-55-04

**Comment by Karinon** [comment]
As I said it is still needed to put the changes to the createTables.sql-file in the other repo aswell. But I wanted to make sure that we are on the same page regarding the structure first

**Comment by antarcticrainforest** [comment]
@eelucio

**Comment by eelucio** [comment]
I think that this is very neat, also in terms of statistics for failures (e.g. times when slurm is down, times when filesystem is unnacessible etc.)

LGTM

**Comment by Karinon** [comment]
need some approval to merge, please

**Review by eelucio — APPROVED** [review]

**Review by antarcticrainforest — APPROVED** [review]

**Pull request merged**
