### PR TITLE
added new freva favicon and banner

### PR DESCRIPTION
**Pull request by eelucio**

### CODE REVIEW

**Review by Karinon — APPROVED** [review]
Niiice! LGTM!

**Comment by Karinon** [comment]
@eelucio Could you send the png-File once through https://tinypng.com/ in order to reduce the file size and re-upload it again?

**Review by antarcticrainforest — APPROVED** [review]

**Comment by antarcticrainforest** [comment]
On thing, can you update the default favicon. Currently it's the ugly fona logo?

**Comment by eelucio** [comment]
I see that we have `favicon.ico` and `favicon-dev.ico` under `static_root/`

should I replace them with our `img/favicon-tmpl.svg` ?


I have been looking in the code and there is no mention to those feva logos. Should we remove them alltogether?

**Comment by eelucio** [comment]
here we go. I hope now it goes well

**Pull request merged**
