### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by Karinon**
- replaced count-numbers in braces or brackets in Data and Result Browser by badges at the end.

- the number of found results in Data Browser is now formatted

- replaced the whitespace at the beginning of each line of the search results in Data Browser by a margin. This has the effect that selecting a file name by double click will no longer select the unnecessary whitespace at the beginning

Screenshot from 2023-03-13 09-23-55

### CODE REVIEW

**Comment by Karinon** [comment]
Stretching the facet count inside the dropdown was not possible in a pretty way as line break can appear there and then it looks completely bad

**Comment by eelucio** [comment]
I do not get very well the last point

> replaced the whitespace at the beginning of each line of the search results in Data Browser by a margin. This has the effect that selecting a file name by double click will no longer select the unnecessary whitespace at the beginning

as I am double click selecting one file and it pastes without whitespace, but maybe I am wrong.

LGTM

**Comment by Karinon** [comment]
Maybe your computer automatically trims the stuff in the clipboard, but it does not for me. Here ist the result of double clicking and pasting in the current xces. It's not a big deal, but I thought this might be annoying to some people

Screenshot from 2023-03-13 09-52-22

**Review by eelucio — APPROVED** [review]

**Comment by eelucio** [comment]
ah, I see. Thanks

sorry, I forgot that here I had to explictly accept the changes, done.

**Review by antarcticrainforest — APPROVED** [review]
LGTM

**Pull request merged**
