### PR TITLE
updated favicon.ico, removed favicon-dev.ico

### PR DESCRIPTION
**Pull request by eelucio**

### CODE REVIEW

**Comment by Karinon** [comment]
1. Why is favicon.ico just an empty transparent file?
2. Why do we need a favicon.ico in the first place? The website is only using the svg, not the ico-file. In my opinion we can delete it aswell. @antarcticrainforest objections?

**Comment by eelucio** [comment]
I have many struggles creating a favicon.ico out of a svg. I did it with imagemagick but neither the oriignal one nor the new one I had any idea how to open them.

if we can ditch that more than better

**Comment by antarcticrainforest** [comment]
Ok you can delete it

**Comment by antarcticrainforest** [comment]
From my side you can merge this.

**Review by Karinon — APPROVED** [review]

**Pull request merged**
